// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwrulrhfgyldmqvhgzgh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3cnVscmhmZ3lsZG1xdmhnemdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDA1NDcsImV4cCI6MjA2MDQ3NjU0N30.AuPWoDTixYbYkqANGs_Q3bhojaGbXoW00UO1kLRDePU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);